on: push

jobs:
  generate_secret:
    name: 'Create service principal'
    runs-on: ubuntu-latest
    steps:

    - name: 'Create SP'
      run: |
        az ad sp create-for-rbac --name "mslearn-k8s" --role contributor \
                                --scopes /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }} \
                                --sdk-auth